[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200
  force = false

[[redirects]]
  from = "/cliente/*"
  to = "/cliente.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
